// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh3ikQAIY27TmhZF5b6JU2maTLlfpf_YI',
    appId: '1:499257875578:web:48b42254d5271905f16fc3',
    messagingSenderId: '499257875578',
    projectId: 'labourskonnect',
    authDomain: 'labourskonnect.firebaseapp.com',
    storageBucket: 'labourskonnect.firebasestorage.app',
    measurementId: 'G-FPJE0M123V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVasBnXwrqLBL7ww7NftWSmfPkCP6sK38',
    appId: '1:499257875578:android:b55415963bfe31aaf16fc3',
    messagingSenderId: '499257875578',
    projectId: 'labourskonnect',
    storageBucket: 'labourskonnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJVbWQs20fECeKCo8NYaOfK_kt8hy85iI',
    appId: '1:499257875578:ios:f5d84a3ab37b0287f16fc3',
    messagingSenderId: '499257875578',
    projectId: 'labourskonnect',
    storageBucket: 'labourskonnect.firebasestorage.app',
    iosBundleId: 'com.example.laboursKonnect',
  );
}
